name: Build Docker

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Login in Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.b v }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Package
        run: npm cache clean --force && npm install

      - name: Build Packages
        run: npm run build

      - name: Build Images
        run: node ./scripts/builder.js build-all -l

      - name: Push Images
        run: node ./scripts/builder.js push-all -l
